[package]
name = "euler387"
version = "0.1.0"
authors = ["Shen Longbin <slofslb@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primes = "0.2"
num-integer = "0.1.42"
